// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiZXFbHGD7-m_TLlGSTnoowTOXZr4bP4c',
    appId: '1:202908665820:web:97dbaef2c1ad607c663119',
    messagingSenderId: '202908665820',
    projectId: 'renthouse-d5d9e',
    authDomain: 'renthouse-d5d9e.firebaseapp.com',
    storageBucket: 'renthouse-d5d9e.firebasestorage.app',
    measurementId: 'G-QN88R3MH8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpzrgHCK-S2dCnI8ovRbElLpDEgNI8cTs',
    appId: '1:202908665820:android:285aee51eceb6193663119',
    messagingSenderId: '202908665820',
    projectId: 'renthouse-d5d9e',
    storageBucket: 'renthouse-d5d9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC73a_0EfOUbqL6GI1L2rfMG_aSuAAGZCs',
    appId: '1:202908665820:ios:5207687661400d1e663119',
    messagingSenderId: '202908665820',
    projectId: 'renthouse-d5d9e',
    storageBucket: 'renthouse-d5d9e.firebasestorage.app',
    iosBundleId: 'com.example.renthouse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiZXFbHGD7-m_TLlGSTnoowTOXZr4bP4c',
    appId: '1:202908665820:web:a7032c36e514b193663119',
    messagingSenderId: '202908665820',
    projectId: 'renthouse-d5d9e',
    authDomain: 'renthouse-d5d9e.firebaseapp.com',
    storageBucket: 'renthouse-d5d9e.firebasestorage.app',
    measurementId: 'G-BCGB2JH5QS',
  );
}
